allowBuilds:
  '@google/genai': true
  '@reown/appkit': true
  bufferutil: true
  esbuild: true
  protobufjs: true
  secp256k1: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@solana/accounts@7.0.0'
  - '@solana/addresses@7.0.0'
  - '@solana/assertions@7.0.0'
  - '@solana/codecs-core@7.0.0'
  - '@solana/codecs-data-structures@7.0.0'
  - '@solana/codecs-numbers@7.0.0'
  - '@solana/codecs-strings@7.0.0'
  - '@solana/codecs@7.0.0'
  - '@solana/errors@7.0.0'
  - '@solana/fast-stable-stringify@7.0.0'
  - '@solana/fixed-points@7.0.0'
  - '@solana/functional@7.0.0'
  - '@solana/instruction-plans@7.0.0'
  - '@solana/instructions@7.0.0'
  - '@solana/keys@7.0.0'
  - '@solana/kit@7.0.0'
  - '@solana/nominal-types@7.0.0'
  - '@solana/offchain-messages@7.0.0'
  - '@solana/options@7.0.0'
  - '@solana/plugin-core@7.0.0'
  - '@solana/plugin-interfaces@7.0.0'
  - '@solana/program-client-core@7.0.0'
  - '@solana/programs@7.0.0'
  - '@solana/promises@7.0.0'
  - '@solana/rpc-api@7.0.0'
  - '@solana/rpc-parsed-types@7.0.0'
  - '@solana/rpc-spec-types@7.0.0'
  - '@solana/rpc-spec@7.0.0'
  - '@solana/rpc-subscriptions-api@7.0.0'
  - '@solana/rpc-subscriptions-channel-websocket@7.0.0'
  - '@solana/rpc-subscriptions-spec@7.0.0'
  - '@solana/rpc-subscriptions@7.0.0'
  - '@solana/rpc-transformers@7.0.0'
  - '@solana/rpc-transport-http@7.0.0'
  - '@solana/rpc-types@7.0.0'
  - '@solana/rpc@7.0.0'
  - '@solana/signers@7.0.0'
  - '@solana/subscribable@7.0.0'
  - '@solana/sysvars@7.0.0'
  - '@solana/transaction-confirmation@7.0.0'
  - '@solana/transaction-introspection@7.0.0'
  - '@solana/transaction-messages@7.0.0'
  - '@solana/transactions@7.0.0'
