import { createUmi } from '@metaplex-foundation/umi-bundle-defaults';
import { create } from '@metaplex-foundation/mpl-core';
import { keypairIdentity, generateSigner, publicKey } from '@metaplex-foundation/umi';
import { readFileSync } from 'fs';

// Update this with the Collection Address generated by setup-collection.ts
const COLLECTION_ADDRESS = 'DrQQhXb2dk99XvhM1Rem7PnKZDkah6C5aFU9Uyd5ju54';

// For testing, we can mint to the admin wallet itself, or replace with a user's wallet
const DESTINATION_WALLET = 'DrQQhXb2dk99XvhM1Rem7PnKZDkah6C5aFU9Uyd5ju54';

async function main() {
  if (COLLECTION_ADDRESS === 'DrQQhXb2dk99XvhM1Rem7PnKZDkah6C5aFU9Uyd5ju54') {
    console.error("❌ Please update COLLECTION_ADDRESS with the output from setup-collection.ts!");
    return;
  }

  const umi = createUmi('https://api.devnet.solana.com');
  const secretKey = new Uint8Array(JSON.parse(readFileSync('./devnet-keypair.json', 'utf8')));
  const keypair = umi.eddsa.createKeypairFromSecretKey(secretKey);
  umi.use(keypairIdentity(keypair));

  console.log(`Minting a pack of 5 stickers to ${DESTINATION_WALLET}...`);

  // Simulate pulling 5 stickers
  for (let i = 1; i <= 5; i++) {
    const assetSigner = generateSigner(umi);
    const stickerId = Math.floor(Math.random() * 29) + 1; // Random ID 1 to 29
    const stickerName = `Zmajevi Sticker #${stickerId}`;

    console.log(`Minting [${i}/5]: ${stickerName}...`);

    await create(umi, {
      asset: assetSigner,
      collection: publicKey(COLLECTION_ADDRESS),
      owner: publicKey(DESTINATION_WALLET), // Transfers ownership immediately to the buyer
      name: stickerName,
      uri: `https://example.com/metadata/${stickerId}.json`, // Points to off-chain traits/image
    }).sendAndConfirm(umi);

    console.log(`✅ Minted! Asset: ${assetSigner.publicKey.toString()}`);
  }

  console.log("🎉 Pack opened successfully!");
}

main().catch(console.error);
